//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchOPharmaWebService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class searchopharmaEntities : DbContext
    {
        public searchopharmaEntities()
            : base("name=searchopharmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DmnMedicine> DmnMedicines { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<Pharmacy> Pharmacies { get; set; }
        public DbSet<SearchMedicine> SearchMedicines { get; set; }
    }
}
