//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApi.Models
{
    public  class Notification
    {
        public int NotificationID { get; set; }
        public string PharmacyID { get; set; }
        public string MedicineID { get; set; }
        public System.DateTime DateTime { get; set; }
        public int MSID { get; set; }
    
        public  MedicineSearch MedicineSearch { get; set; }
        public Pharmacy Pharmacy { get; set; }
    }
}
