//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApi.Models
{ 
    public  class Pharmacy
    {
        public int PharmacyID { get; set; }
        public string PharmacyName { get; set; }
        public string Address { get; set; }

        public Notification Notification { get; set; }
        
        public MedicineSearch MedicineSearch { get; set; }
        public Medicine Medicine { get; set; }
    }
}
